Repository masonitedoors/MDL, pull requests merged in 2019-10, with the labels that each got.

#80 #76 - Fix anchor tag having explicit font size
  components/typography/react.stories.js
  styles/_typography.scss
Labels: bug

#82 #81 fix text field value overlap w trailing icon
  components/TextField/react.js
  components/TextField/react.stories.js
  components/TextField/style.module.scss
Labels: bug

#84 Move styles to stylesheet that is imported once
  styles/global.scss
  styles/index.scss
Labels: foundation

#86 Allow TextField value to be null
  components/TextField/react.js
  packages/external-ui-react/CHANGELOG.md
Labels: bug, component

#90 Fix hot-reloading error when linting issue arises
  .storybook/react/webpack.config.js
  package-lock.json
  package.json
Labels: bug, utility work

#89 Pagination
  .storybook/react/addons.js
  components/Button/react.js
  components/Pagination/__snapshots__/react.test.js.snap
  components/Pagination/generateVisiblePages.js
  components/Pagination/generateVisiblePages.test.js
  components/Pagination/index.js
  components/Pagination/react.js
  components/Pagination/react.stories.js
  components/Pagination/react.test.js
  components/Pagination/style.module.scss
  package.json
Labels: component
